---
title: "R Notebook"
output: html_notebook
---


Use matrix of parameter to simulate landscapes

```{r}
library(NLMR)
library(landscapetools)
library(raster)
library(dplyr)
library(purrr)
library(tibble)
```

```{r}
# simulation function that has the parameters we want to alter as input
simulate_landscape = function(roughness, weighting){
    nlm_mpd(ncol = 33,
            nrow = 33,
            roughness = roughness,
            rescale = TRUE) %>%
        util_classify(weighting = weighting)
}
```

```{r}
# parameter combinations we are interested in
param_df = expand.grid(roughness = c(0.2, 0.9),
                       weighting = list(c(0.2, 0.8), c(0.2, 0.3, 0.5))) %>%
    as_tibble()

# map over the nested tibble and use each row as input for our simulation function
nlm_list = param_df %>% pmap(simulate_landscape)

# look at the results
show_landscape(nlm_list)

```
Simulate ecotones
Merging different types of NLMs, such as a planar gradient with a less autocorrelated landscape, provide a means of generating more complex landscapes and realistic-looking ecotones (Travis 2004):

```{r}
library(NLMR)
library(landscapetools)

# landscape with higher autocorrelation 
high_autocorrelation <- nlm_edgegradient(ncol = 100, nrow = 100, direction = 80)

# landscape with lower autocorrelation 
low_autocorrelation <- nlm_fbm(ncol = 100, nrow = 100, fract_dim = 0.5)

# merge to derive ecotone
ecotones <- util_merge(low_autocorrelation, high_autocorrelation)

# look at the results
show_landscape(list("Low autocorrelation" = low_autocorrelation,
                    "High autocorrelation" = high_autocorrelation,
                    "Ecotones" = ecotones
                    ))
```

